### CREATE
POST http://localhost:5000/api/magang/anggota/bulk
Content-Type: application/json

{
    "mahasiswaList": [
        { "id_mahasiswa": 1, "id_daftar": 1 },
        { "id_mahasiswa": 2, "id_daftar": 1 }
    ]
}

### GET ALL WITH QUERY
GET http://localhost:5000/api/magang/anggota?id_dosen=1&id_mahasiswa=1

### GET BY ID
GET http://localhost:5000/api/magang/anggota/25

### GET BY DAFTAR & BY MHS
GET http://localhost:5000/api/magang/anggota/pengajuan/1/mahasiswa/1

### DELETE BY ID
DELETE http://localhost:5000/api/magang/anggota/8