### GET
GET http://localhost:5000/api/logbook

### GET Logbook By Mahasiswa
GET http://localhost:5000/api/logbook/mahasiswa/1

### POST Create Logbook 
POST http://localhost:5000/api/logbook
Content-Type: application/json

{
    "id_mahasiswa": 2,
    "tanggal": "2024-10-14",
    "jam_mulai": "08:00",
    "jam_selesai": "16:00",
    "kegiatan": "Test Logbook",
    "kesesuaian_matkul_diajarkan": 0,
    "matkul_diajarkan": null,
    "setujui_logbook": 1,
    "lampiran_laporan": null,
    "lampiran_foto": null,
    "catatan_pembimbing": null
}

### POST Logbook By Mahasiswa
POST http://localhost:5000/api/logbook/mahasiswa
Content-Type: application/json

{
    "id_mahasiswa": 1
}

### DELETE Logbook
DELETE http://localhost:5000/api/logbook/5

### PUT Create Monitoring Logbook
PUT http://localhost:5000/api/logbook/monitoring/1
Content-Type: application/json

{
    "catatan_pembimbing": "Oke lanjutkan"
}
