### CREATE
POST http://localhost:5000/api/magang/pengajuan
Content-Type: application/json

{
    "lama_kp": "KP3Pertama",
    "tempat_kp": "Badan Perencanaan Pembangunan Daerah",
    "alamat": "Jl. P Mas Tumapel",
    "kota": "Bojonegoro",
    "id_mahasiswa": 1
}

### UPDATE BY ID
PUT http://localhost:5000/api/magang/pengajuan/1
Content-Type: application/json

{
    "lama_kp": "KP3Pertama",
    "tempat_kp": "Badan Perencanaan Pembangunan Daerah",
    "alamat": "Jl. P Mas Tumapel",
    "kota": "Bojonegoro"
}

### GET BY ID
GET http://localhost:5000/api/magang/pengajuan/1

### GET
GET http://localhost:5000/api/magang

###
GET http://localhost:5000/api/magang/pengajuan/1/anggota

### VERIFIKASI BY ID
PUT http://localhost:5000/api/magang/pengajuan/10/verifikasi
Content-Type: application/json

{
    "status_persetujuan": 0,
    "tanggal_kp": "2024-08-26",
    "catatan_koordinator_kp": null
}

### VERIFIKASI BY ID
PUT http://localhost:5000/api/magang/pengajuan/1/ploting
Content-Type: application/json

{
    "id_dosen": "3"
}