### GET
GET http://localhost:5000/api/dosen

### GET BY ID
GET http://localhost:5000/api/dosen/1

### DELETE BY ID
DELETE http://localhost:5000/api/dosen/1

### CREATE
POST http://localhost:5000/api/dosen
Content-Type: application/json

{
    "nip": "123456789012345678",
    "nama": "Viki Fitria, M.Pd.",
    "jenis_kelamin": "Perempuan",
    "email": "vikifitria@gmail.com",
    "nomor_hp": "085235385077",
    "alamat": "Bojonegoro"
}

### UPDATE BY ID
PUT http://localhost:5000/api/dosen/5
Content-Type: application/json

{
    "nip": "123456789012345678",
    "nama": "Viki Fitria, M.Pd.",
    "jenis_kelamin": "Perempuan",
    "email": "vikifitria@gmail.com",
    "nomor_hp": "085235385077",
    "alamat": "Bojonegoro"
}

### GET LAPORAN PLOTING DOSEN
GET http://localhost:5000/api/dosen/ploting