### POST Login
POST http://localhost:5000/api/auth/signin
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}

### POST Logout
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

### POST Refresh Token
POST http://localhost:5000/api/auth/refresh
Content-Type: application/json